name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - graphviz
  - ipykernel
  - matplotlib
  - nltk
  - numpy
  - pip
  - pip:
    - jupyter-book
    - jupyterlab_rise
    - svgling
